CREATE TABLE user (
    id MEDIUMINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(250),
    email VARCHAR(100),
    encrypted_password VARCHAR(65),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE metric (
    id MEDIUMINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(250),
    PRIMARY KEY (id)
);
